server:
  port: 8762
spring:
  application:
    name: travel-management-zuul-server
check:
  token:
    endpoint: http://localhost:8762/oauth/check_token
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    travel-management-auth-server:
      path: /oauth/**
      serviceId: travel-management-auth-server
      strip-prefix: false
    travel-management-customer-api:
      path: /customer/**
      serviceId: travel-management-customer-api
      strip-prefix: false
    travel-management-employee-api:
      path: /employee/**
      serviceId: travel-management-employee-api
      strip-prefix: false
    travel-management-trip-api:
      path: /trip/**
      serviceId: travel-management-trip-api
      strip-prefix: false
    travel-management-trip-summary-api:
      path: /trip-summary/**
      serviceId: travel-management-trip-summary-api
      strip-prefix: false